cargo-features = ["edition2024"]
[package]
name = "gauntlet-utils-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
convert_case = "0.8.0"
proc-macro2 = "1.0.92"
